# 🍽️ Restaurant Data Cleanup & Inspection
### LA Luxury Restaurant Recommendation System — Phase 1

**Purpose:** Load, inspect, clean, and validate the `cleaned_restaurants_list.csv` dataset  
**Dataset:** 100 upscale & Michelin-rated restaurants in Los Angeles County  
**Output:** A clean, validated `cleaned_restaurants_final.csv` ready for vector embedding and LLM processing

---
**Columns in Dataset:**
| Column | Description |
|--------|-------------|
| `Name` | Restaurant name |
| `Location` | City/neighborhood |
| `Description` | One-sentence summary |
| `Address` | Full street address |
| `Telephone Number` | Phone number |
| `Price` | Dollar sign scale (\$ to \$\$\$\$\$) |
| `Cuisine Type` | Cuisine category |
| `Dining Atmosphere` | Vibe/atmosphere |
| `Sky-High Rooftop` | Yes/No — rooftop/top-floor location |
| `Michelin-Guide` | Michelin designation or No |
| `Customer Ratings` | Aggregated rating (1.0–5.0) |
| `Operation Hours` | Hours of operation |
| `Reservations` | Reservation policy |
| `Dress Code` | Dress code requirement |

## 📦 Cell 1 — Import Libraries

In [5]:
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings("ignore")

# Display settings — show all columns and full text
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_colwidth', 120)
pd.set_option('display.width', 250)

print("✅ Libraries loaded successfully.")

✅ Libraries loaded successfully.

## 📂 Cell 2 — Load the Dataset

> **Note:** Place `cleaned_restaurants_list.csv` in the same folder as this notebook,  
> or update the path below to point to your file location.

In [ ]:
# ---------------------------------------------------------
# UPDATE THIS PATH if your CSV is in a different location
# ---------------------------------------------------------
CSV_PATH = "../data/cleaned_restaurants_list.csv"

df = pd.read_csv(CSV_PATH)

print(f"✅ Dataset loaded successfully!")
print(f"   Rows    : {df.shape[0]}")
print(f"   Columns : {df.shape[1]}")
print(f"\nColumn names:")
for i, col in enumerate(df.columns, 1):
    print(f"   {i:>2}. {col}")

✅ Dataset loaded successfully!
   Rows    : 94
   Columns : 14

Column names:
    1. Name
    2. Location
    3. Description
    4. Address
    5. Telephone Number
    6. Price
    7. Cuisine Type
    8. Dining Atmosphere
    9. Sky-High Rooftop
   10. Michelin-Guide
   11. Customer Ratings
   12. Operation Hours
   13. Reservations
   14. Dress Code

## 🔍 Cell 3 — Initial Data Preview

In [7]:
# Preview the first 10 rows
print("=== FIRST 10 ROWS ===")
df.head(10)

=== FIRST 10 ROWS ===

,Name,Location,Description,Address,Telephone Number,Price,Cuisine Type,Dining Atmosphere,Sky-High Rooftop,Michelin-Guide,Customer Ratings,Operation Hours,Reservations,Dress Code
0,Somni,West Hollywood,A 14-seat Spanish Modernist chef's counter offering a 20+ course tasting menu led by Chef Aitor Zabala with one seat...,"9045 Nemo St, West Hollywood, CA 90069",Number Not Listed,$$$$$,Spanish Modernist,Fine-Dining,No,3-Star,5.0,Wed-Sun 7:30pm (one seating),Reservation Only,No
1,Providence,Hollywood,A celebrated seafood-forward fine dining institution from Chef Michael Cimarusti with nearly 20 years of Michelin re...,"5955 Melrose Ave, Los Angeles, CA 90038",(323) 460-4170,$$$$,Seafood / Contemporary,Fine-Dining,No,3-Star,5.0,Tue-Thu 6pm-9pm / Fri-Sat 5:30pm-9:30pm,Reservation Only,No
2,Hayato,Downtown Arts District,A 7-seat intimate kaiseki restaurant from Chef Brandon Go serving traditional Japanese multi-course dinners with han...,"1320 E 7th St Suite 126, Los Angeles, CA 90021",(213) 395-0607,$$$$,Japanese Kaiseki,Fine-Dining,No,2-Star,5.0,Tue-Sat (one seating nightly),Reservation Only,No
3,n/naka,Palms,A serene 13-course modern kaiseki restaurant from Netflix Chef's Table star Niki Nakayama blending Japanese and Cali...,"3455 Overland Ave, Los Angeles, CA 90034",(310) 836-6252,$$$$,Japanese Kaiseki,Fine-Dining,No,2-Star,5.0,Wed-Sun 5:30pm-9pm,Reservation Only,Strict
4,Melisse,Santa Monica,A hidden 14-seat fine dining alcove within sister restaurant Citrin offering a luxurious and frequently changing sea...,"1104 Wilshire Blvd, Santa Monica, CA 90401",(310) 395-0881,$$$$,French / Contemporary American,Fine-Dining,No,2-Star,4.0,Tue-Sat (dinner only),Reservation Only,Yes
5,Vespertine,Culver City,An avant-garde two-Michelin-star dining experience from Chef Jordan Kahn set inside a wavy obelisk architectural mar...,"3599 Hayden Ave, Culver City, CA 90232",(323) 320-4023,$$$$,Contemporary American / Innovative,Fine-Dining,No,2-Star,5.0,Wed-Sun (one seating nightly),Reservation Only,No
6,Sushi Kaneyoshi,Little Tokyo,A highly exclusive omakase sushi experience tucked in Little Tokyo offering pristine seasonal fish in an intimate co...,"250 1st St B1, Los Angeles, CA 90012",(213) 277-2388,$$$$,Japanese / Sushi,Fine-Dining,No,1-Star,5.0,Tue-Sat (dinner seatings),Reservation Only,No
7,Restaurant Ki,Little Tokyo,A 10-seat subterranean Korean contemporary tasting menu hidden in a hard-to-find backroom offering an intimate and i...,"111 San Pedro St, Los Angeles, CA 90012",(213) 786-3154,$$$$,Korean Contemporary,Fine-Dining,No,1-Star,5.0,Wed-Sun (dinner only),Reservation Only,No
8,715 Sushi,Downtown Los Angeles,A minimalist omakase sushi counter in the Arts District offering a chef's choice multi-course menu with rustic Japan...,"738 E 3rd St, Los Angeles, CA 90013",(213) 547-0459,$$$$,Japanese / Sushi,Fine-Dining,No,1-Star,5.0,Tue-Sat (dinner only),Reservation Only,No
9,Orsa & Winston,Downtown Los Angeles,An intimate fine dining restaurant offering a creative contemporary tasting menu with Italian and Japanese influences.,"122 W 4th St, Los Angeles, CA 90013",(213) 687-0300,$$$$,Contemporary,Fine-Dining,No,1-Star,4.8,Tue-Sat (dinner only),Reservation Only,No

In [8]:
# Preview the last 10 rows
print("=== LAST 10 ROWS ===")
df.tail(10)

=== LAST 10 ROWS ===

,Name,Location,Description,Address,Telephone Number,Price,Cuisine Type,Dining Atmosphere,Sky-High Rooftop,Michelin-Guide,Customer Ratings,Operation Hours,Reservations,Dress Code
84,Sampa Los Angeles,Downtown Los Angeles,Sampa is a trendy eatery in Downtown L.A's Arts District with a evolutionary focus on elevated Filipino-American cui...,"449 S Hewitt St, Los Angeles, CA 90013",(213) 935-8119,$$$$,Asian / New American,Trendy,No,Michelin-Selected,4.5,Tue-Thurs 5pm-10pm / Fri-Sat 5pm-11pm / Sun 10am-10:00pm,Reservation Only,No
85,RVR,Venice,RVR is an all-day Japanese Izakaya / Tavern which combines the epic traditions of everyday Japanese drinking fare wi...,"1305 Abbot Kinney Blvd, Venice, CA 90291",(310) 573-8077,$$,Japanese Izakaya,Casual,No,No,4.1,Mon-Thurs 5pm-11pm / Fri-Sat 11am-11pm / Sun 11am-10:00pm,Yes,No
86,Laurel Hardware,West Hollywood,"Hip farm-to-table restaurant in a former hardware store serving a seasonal, organic, farmers' market menu with signa...","7984 Santa Monica Blvd, West Hollywood, CA 90046",(323) 656-6070,$$$,New American,Trendy,No,No,3.9,Mon-Wed 5pm-11:30pm / Thurs-Fri 5pm-12am / Sat-Sun 12pm-11pm,No,No
87,Crustacean,Beverly Hills,Renowned seafood & creative Vietnamese fare dished up in chic digs with an attention-getting aquarium. Experience th...,"468 N Bedford Dr, Beverly Hills, CA 90210",(310) 205-8990,$$$$,Asian / Vietnamese,Fine-Dining,No,Michelin-Selected,4.7,Wed-Sat 12pm-8pm / Tue-Sun 5pm-9:30pm / Sun 11:30am-3pm,Reservation Only,Yes
88,Mainro (MainR6),Hollywood,Hollywood's newest restaurant & supper club that provides a senses-stimulating experience that's smart & sophisticat...,"6350 Hollywood Blvd, Los Angeles, CA 90028",(323) 378-6778,$$$$,Asian Fusion,Trendy / Vibrant,No,No,4.1,Wed-Thurs 7:30pm-1am / Fri-Sat 6:30pm-2am,Reservation Only,Yes
89,Broken Spanish Comedor,Culver City,"This spot is a neighborhood offshoot of Broken Spanish with the same qualiy but with a community-centric approach, o...","12565 Washington Blvd, Los Angeles, CA 90066",(747) 946-7118,$$$,New Mexican,Trendy / Casual,No,No,4.7,"Daily (brunch, happy hour, & dinner)",No,No
90,Night We Met,Los Angeles,"Located in the Wilshire LaBrea Apartments & Opened by the duo behind Met Her at a Bar, it features a romantic, vibra...","788 S La Brea Ave, Los Angeles, CA 90036",(323) 424-3108,$$$,Pan Asian,Romantic / Smart-Casual,No,No,4.4,Mon-Thurs 5pm-11:30pm / Fri 5pm-1am / Sat-Sun 11am-1am,No,Yes
91,Sora Craft Kitchen,Downtown Los Angeles,A one-man show run by Chef Okay Inak. This Turkish-born chef has a fine dining pedigree but runs this DTLA spot enti...,"1109 East 12th Street, Los Angeles, CA 90021",(213) 537-0654,$$$,Turkish,Romantic / Smart-Casual,No,Michelin-Selected,4.8,Thurs-Sun 5pm-10pm,Reservation Only,Yes
92,Delilah,West Hollywood,Delilah brings a modern approach to the vibes of the roaring ‘20s. Lavish chandeliers hang overhead and olive green ...,"7969 Santa Monica Blvd, West Hollywood, CA 90046",(323) 745-0600,$$$,New American,Upscale / Fine-Dining,No,No,4.1,Tue-Sun 6:30pm-2am,Reservation Only,Yes
93,Catch LA,West Hollywood,Catch LA enters a new era with a renewed food-first mentality and a sharpened focus on service & experience. The res...,"8715 Melrose Ave, West Hollywood, CA 90069",(323) 347-6060,$$$,Japanese / New American,Romantic / Smart-Casual,Yes,No,4.7,Mon-Wed 6pm-9pm / Thurs 6pm-10pm / Fri-Sat 5:30pm-10:30pm / Sun 6pm-9:30pm,Yes,Yes

## 📊 Cell 4 — Data Types & Structure

In [9]:
print("=== DATA TYPES ===")
print(df.dtypes)

print("\n=== DATAFRAME INFO ===")
df.info()

=== DATA TYPES ===
Name                     str
Location                 str
Description              str
Address                  str
Telephone Number         str
Price                    str
Cuisine Type             str
Dining Atmosphere        str
Sky-High Rooftop         str
Michelin-Guide           str
Customer Ratings     float64
Operation Hours          str
Reservations             str
Dress Code               str
dtype: object

=== DATAFRAME INFO ===
<class 'pandas.DataFrame'>
RangeIndex: 94 entries, 0 to 93
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               94 non-null     str
 1   Location           94 non-null     str
 2   Description        94 non-null     str
 3   Address            94 non-null     str
 4   Telephone Number   94 non-null     str
 5   Price              94 non-null     str
 6   Cuisine Type       94 non-null     str
 7   Dining Atmosphere  94 non-null     str
 8   Sky-High Rooftop   94 non-null     str
 9   Michelin-Guide     94 non-null     str
 10  Customer Ratings   94 non-null     float64
 11  Operation Hours    94 non-null     str
 12  Reservations       94 non-null     str
 13  Dress Code         94 non-null     str
dtypes: float64(1), str(13)
memory usage: 40.4 KB

## ❓ Cell 5 — Missing Value Check

In [10]:
print("=== MISSING VALUES PER COLUMN ===")
missing = df.isnull().sum()
missing_pct = (df.isnull().sum() / len(df) * 100).round(2)

missing_report = pd.DataFrame({
    'Missing Count': missing,
    'Missing %': missing_pct
})

print(missing_report)

if missing.sum() == 0:
    print("\n✅ No missing values found in any column.")
else:
    print(f"\n⚠️  Total missing cells: {missing.sum()}")

=== MISSING VALUES PER COLUMN ===
                   Missing Count  Missing %
Name                           0        0.0
Location                       0        0.0
Description                    0        0.0
Address                        0        0.0
Telephone Number               0        0.0
Price                          0        0.0
Cuisine Type                   0        0.0
Dining Atmosphere              0        0.0
Sky-High Rooftop               0        0.0
Michelin-Guide                 0        0.0
Customer Ratings               0        0.0
Operation Hours                0        0.0
Reservations                   0        0.0
Dress Code                     0        0.0

✅ No missing values found in any column.

## 🔢 Cell 6 — Descriptive Statistics (Numeric Columns)

In [11]:
print("=== DESCRIPTIVE STATISTICS — Customer Ratings ===")
print(df['Customer Ratings'].describe())

print("\n=== RATING DISTRIBUTION ===")
print(df['Customer Ratings'].value_counts().sort_index(ascending=False))

=== DESCRIPTIVE STATISTICS — Customer Ratings ===
count    94.000000
mean      4.503191
std       0.425138
min       3.000000
25%       4.300000
50%       4.600000
75%       4.800000
max       5.000000
Name: Customer Ratings, dtype: float64

=== RATING DISTRIBUTION ===
Customer Ratings
5.0    16
4.9     4
4.8     7
4.7    11
4.6    11
4.5    11
4.4     4
4.3    10
4.2     4
4.1     3
4.0     7
3.9     2
3.8     1
3.0     3
Name: count, dtype: int64

## 📋 Cell 7 — Categorical Column Value Counts

In [12]:
categorical_cols = [
    'Price', 'Cuisine Type', 'Dining Atmosphere',
    'Sky-High Rooftop', 'Michelin-Guide', 'Reservations', 'Dress Code'
]

for col in categorical_cols:
    print(f"\n=== {col.upper()} ===")
    print(df[col].value_counts().to_string())

=== PRICE ===
Price
$$$$     48
$$$      25
$$       13
$$$$$     5
$         3

=== CUISINE TYPE ===
Cuisine Type
Italian                               7
Steakhouse                            5
Japanese Omakase                      4
Contemporary American                 4
Japanese Kaiseki                      3
Japanese / Sushi                      3
Contemporary                          3
Japanese                              3
Asian / Taiwanese                     3
Korean Contemporary                   2
Californian                           2
Mexican                               2
Steakhouse / Seafood                  2
Italian / Modernist                   2
Indian                                2
Korean                                2
Japanese / Peruvian                   2
New American                          2
Spanish Modernist                     1
Seafood / Contemporary                1
French / Contemporary American        1
Contemporary American / Innovative    1
French                                1
Mexican / Seafood                     1
American Steakhouse                   1
Global / Contemporary                 1
Italian-American                      1
Pizza                                 1
Deli                                  1
Barbecue                              1
Malaysian                             1
Italian / Tuscan                      1
Seafood / Steakhouse                  1
Japanese / Steakhouse                 1
Steakhouse / Sushi                    1
Teppanyaki                            1
Spanish                               1
Brazilian Steakhouse                  1
American                              1
Asian                                 1
Mediterranean / French-Californian    1
French / Mediterranean                1
Japanese / Brazilian                  1
Nordic-Californian                    1
Asian / Indonesian                    1
Persian                               1
Italian / Milanese                    1
Seafood                               1
Contemporary American / Seafood       1
New American / Steakhouse             1
New American / Latin                  1
Asian / New American                  1
Japanese Izakaya                      1
Asian / Vietnamese                    1
Asian Fusion                          1
New Mexican                           1
Pan Asian                             1
Turkish                               1
Japanese /  New American              1

=== DINING ATMOSPHERE ===
Dining Atmosphere
Fine-Dining                43
Casual                     18
Trendy                     12
Romantic / Smart-Casual     6
Smart-Casual                4
Romantic                    3
Trendy / Smart-Casual       3
Upscale / Fine-Dining       2
Fine-Casual                 1
Trendy / Vibrant            1
Trendy / Casual             1

=== SKY-HIGH ROOFTOP ===
Sky-High Rooftop
No     82
Yes    12

=== MICHELIN-GUIDE ===
Michelin-Guide
No                   42
1-Star               21
Michelin-Selected    15
Bib-Gourmand         10
2-Star                4
3-Star                2

=== RESERVATIONS ===
Reservations
Yes                 50
Reservation Only    32
No                  12

=== DRESS CODE ===
Dress Code
No        71
Yes       21
Strict     2

## 🔎 Cell 8 — Unique Neighborhoods / Locations

In [13]:
print("=== UNIQUE LOCATIONS (Neighborhoods) ===")
locations = sorted(df['Location'].unique())
for loc in locations:
    count = (df['Location'] == loc).sum()
    print(f"  {loc:<30} ({count} restaurant{'s' if count > 1 else ''})")

print(f"\nTotal unique neighborhoods: {len(locations)}")

=== UNIQUE LOCATIONS (Neighborhoods) ===
  Beverly Hills                  (10 restaurants)
  Brentwood                      (1 restaurant)
  Burbank                        (1 restaurant)
  Chinatown                      (1 restaurant)
  Culver City                    (2 restaurants)
  Downtown Arts District         (2 restaurants)
  Downtown Los Angeles           (25 restaurants)
  Echo Park                      (2 restaurants)
  Encino                         (2 restaurants)
  Granada Hills                  (1 restaurant)
  Hollywood                      (9 restaurants)
  Hollywood Hills                (1 restaurant)
  Koreatown                      (2 restaurants)
  Larchmont Village              (1 restaurant)
  Lincoln Heights                (1 restaurant)
  Little Tokyo                   (3 restaurants)
  Long Beach                     (1 restaurant)
  Los Angeles                    (4 restaurants)
  Malibu                         (2 restaurants)
  Manhattan Beach                (1 restaurant)
  Marina Del Rey                 (1 restaurant)
  Palms                          (1 restaurant)
  Santa Monica                   (6 restaurants)
  Silver Lake                    (2 restaurants)
  South Los Angeles              (1 restaurant)
  Torrance                       (1 restaurant)
  Venice                         (1 restaurant)
  West Hollywood                 (7 restaurants)
  West Los Angeles               (1 restaurant)
  Westlake                       (1 restaurant)

Total unique neighborhoods: 30

## 🧹 Cell 9 — Data Quality: Trailing Whitespace Check

Whitespace at the start or end of string values can cause silent bugs  
in filtering, searching, and vector embedding. We strip all text columns.

In [14]:
string_cols = df.select_dtypes(include='object').columns.tolist()

print("=== CHECKING FOR TRAILING/LEADING WHITESPACE ===")
issues_found = False

for col in string_cols:
    mask = df[col].str.strip() != df[col]
    if mask.any():
        issues_found = True
        print(f"\n⚠️  Column '{col}' — {mask.sum()} row(s) with whitespace:")
        for idx in df[mask].index:
            print(f"   Row {idx} ({df.loc[idx, 'Name']}): {repr(df.loc[idx, col][-30:])}")

if not issues_found:
    print("✅ No whitespace issues found.")

# --- FIX: Strip all string columns ---
for col in string_cols:
    df[col] = df[col].str.strip()

print("\n✅ All string columns stripped of leading/trailing whitespace.")

=== CHECKING FOR TRAILING/LEADING WHITESPACE ===

⚠️  Column 'Name' — 2 row(s) with whitespace:
   Row 79 (Castaway ): 'Castaway '
   Row 87 (Crustacean ): 'Crustacean '

⚠️  Column 'Description' — 4 row(s) with whitespace:
   Row 66 (Elephante): 'to feel like a beach getaway. '
   Row 81 (SALT Restaurant & Bar): 'ents from local land and sea.\xa0'
   Row 89 (Broken Spanish Comedor): 'ornia’s modern sensibilities.\xa0'
   Row 92 (Delilah): 'are by a crackling fireplace.\xa0'

⚠️  Column 'Address' — 3 row(s) with whitespace:
   Row 7 (Restaurant Ki): 'dro St, Los Angeles, CA 90012 '
   Row 32 (Rasarumah): 'y Blvd, Los Angeles, CA 90026 '
   Row 49 (H&H Brazilian Steakhouse): 'th St., Los Angeles, CA 90014 '

⚠️  Column 'Cuisine Type' — 1 row(s) with whitespace:
   Row 76 (Perse): 'Persian '

⚠️  Column 'Operation Hours' — 2 row(s) with whitespace:
   Row 79 (Castaway ): '1am-9pm / Thurs-Sat 11am-11pm '
   Row 83 (Uca Terraza): 's-Sat 4pm-12am / Sun 4pm-10pm '

✅ All string columns stripped of leading/trailing whitespace.

## 🔁 Cell 10 — Duplicate Name Check

Some restaurants intentionally appear twice because they have multiple locations  
(e.g., Pine & Crane in DTLA and Silver Lake, Badmaash in Hollywood and DTLA).  
These are **valid duplicates** — we confirm they have different addresses.

In [15]:
print("=== DUPLICATE RESTAURANT NAMES ===")
dupes = df[df.duplicated('Name', keep=False)].copy()

if dupes.empty:
    print("✅ No duplicate names found.")
else:
    print(f"Found {len(dupes)} rows with shared names (may be intentional multi-location restaurants):\n")
    print(dupes[['Name', 'Location', 'Address', 'Michelin-Guide']].to_string(index=True))

# --- Check for EXACT duplicate rows (same name AND same address) ---
print("\n=== EXACT DUPLICATE ROWS (same Name + Address) ===")
exact_dupes = df[df.duplicated(subset=['Name', 'Address'], keep=False)]
if exact_dupes.empty:
    print("✅ No exact duplicate rows found — multi-location entries are legitimately distinct.")
else:
    print(f"⚠️  {len(exact_dupes)} rows are exact duplicates:")
    print(exact_dupes[['Name', 'Location', 'Address']].to_string())

=== DUPLICATE RESTAURANT NAMES ===
Found 4 rows with shared names (may be intentional multi-location restaurants):

            Name              Location                                           Address     Michelin-Guide
34  Pine & Crane  Downtown Los Angeles  1120 S Grand Ave Unit 101, Los Angeles, CA 90015       Bib-Gourmand
35  Pine & Crane           Silver Lake    1521 Griffith Park Blvd, Los Angeles, CA 90026       Bib-Gourmand
51      Badmaash             Hollywood          418 N Fairfax Ave, Los Angeles, CA 90036  Michelin-Selected
52      Badmaash  Downtown Los Angeles       108 W 2nd St Apt 104, Los Angeles, CA 90012  Michelin-Selected

=== EXACT DUPLICATE ROWS (same Name + Address) ===
✅ No exact duplicate rows found — multi-location entries are legitimately distinct.

## 📍 Cell 11 — Address Format Inspection

Checks for formatting inconsistencies in the `Address` column  
that could affect geocoding or display.

In [16]:
print("=== ALL ADDRESSES ===")
for i, row in df.iterrows():
    print(f"  [{i:>2}] {row['Name']:<35} | {row['Address']}")

# Flag addresses missing a comma before state abbreviation (e.g., 'Malibu CA' vs 'Malibu, CA')
print("\n=== ADDRESSES MISSING COMMA BEFORE STATE ===")
import re
bad_format = df[df['Address'].str.contains(r'[a-zA-Z]\s+CA\s', regex=True) 
                & ~df['Address'].str.contains(r',\s*CA', regex=True)]
if bad_format.empty:
    print("✅ All addresses have proper comma before state.")
else:
    print(f"⚠️  {len(bad_format)} address(es) missing comma before CA:")
    print(bad_format[['Name', 'Address']].to_string())

=== ALL ADDRESSES ===
  [ 0] Somni                               | 9045 Nemo St, West Hollywood, CA 90069
  [ 1] Providence                          | 5955 Melrose Ave, Los Angeles, CA 90038
  [ 2] Hayato                              | 1320 E 7th St Suite 126, Los Angeles, CA 90021
  [ 3] n/naka                              | 3455 Overland Ave, Los Angeles, CA 90034
  [ 4] Melisse                             | 1104 Wilshire Blvd, Santa Monica, CA 90401
  [ 5] Vespertine                          | 3599 Hayden Ave, Culver City, CA 90232
  [ 6] Sushi Kaneyoshi                     | 250 1st St B1, Los Angeles, CA 90012
  [ 7] Restaurant Ki                       | 111 San Pedro St, Los Angeles, CA 90012
  [ 8] 715 Sushi                           | 738 E 3rd St, Los Angeles, CA 90013
  [ 9] Orsa & Winston                      | 122 W 4th St, Los Angeles, CA 90013
  [10] Camphor                             | 923 E 3rd St Suite 109, Los Angeles, CA 90013
  [11] Morihiro                            | 1115 W. Sunset Blvd Suite 100 Los Angeles, CA 90012
  [12] Kato                                | 777 S. Alameda St. Building 1, Suite 114 Los Angeles, CA 90021
  [13] Holbox                              | 3655 S Grand Ave, Los Angeles, CA 90007
  [14] Gwen Butcher Shop & Restaurant      | 6600 Sunset Blvd, Los Angeles, CA 90028
  [15] Heritage                            | 2030 E 7th St, Long Beach, CA 90804
  [16] Sushi Inaba                         | 20918 Hawthorne Blvd., Torrance, CA 90503
  [17] Kali                                | 5722 Melrose Ave, Los Angeles, CA 90038
  [18] Citrin                              | 1104 Wilshire Blvd, Santa Monica, CA 90401
  [19] Gucci Osteria                       | 347 N Rodeo Dr, Beverly Hills, CA 90210
  [20] Meteora                             | 6703 Melrose Ave, Los Angeles, CA 90038
  [21] Mori Nozomi                         | 11500 W Pico Blvd, Los Angeles, CA 90064
  [22] Nozawa Bar                          | 212 N Canon Dr, Beverly Hills, CA 90210
  [23] Pasta | Bar                         | 16101 Ventura Blvd #255, Encino, CA 91436
  [24] Shin Sushi                          | 16573 Ventura Blvd, Encino, CA 91436
  [25] Uka at Japan House                  | 6801 Hollywood Blvd 4th Floor, Hollywood, CA 90028
  [26] Maccheroni Republic                 | 332 S Broadway, Los Angeles, CA 90013
  [27] The Factory Kitchen                 | 1300 Factory Pl, Los Angeles, CA 90013
  [28] Pizzeria Bianco                     | 1320 E 7th St, Suite 100, Los Angeles, CA 90021
  [29] Tsubaki                             | 1356 Allison Ave, Los Angeles, CA 90026
  [30] Langer's                            | 704 S Alvarado St, Los Angeles, CA 90057
  [31] Moo's Craft Barbecue                | 2118 N. Broadway, Los Angeles, CA 90031
  [32] Rasarumah                           | 3107 Beverly Blvd, Los Angeles, CA 90026
  [33] Komal                               | 3655 S Grand Ave Space C-9, Los Angeles, CA 90007
  [34] Pine & Crane                        | 1120 S Grand Ave Unit 101, Los Angeles, CA 90015
  [35] Pine & Crane                        | 1521 Griffith Park Blvd, Los Angeles, CA 90026
  [36] 71Above                             | 633 W 5th St 71st Floor, Los Angeles, CA 90071
  [37] CUT by Wolfgang Puck                | 9500 Wilshire Blvd, Beverly Hills, CA 90212
  [38] Osteria Mozza                       | 6602 Melrose Ave, Los Angeles, CA 90038
  [39] Chi Spacca                          | 6610 Melrose Ave, Los Angeles, CA 90038
  [40] La Boucherie                        | 900 Wilshire Blvd fl 71, Los Angeles, CA 90017
  [41] Mastro's Ocean Club                 | 18412 Pacific Coast Hwy., Malibu CA 90265
  [42] Ocean Prime                         | 9595 Wilshire Blvd, Beverly Hills, CA 90212
  [43] Bestia                              | 2121 E 7th Pl, Los Angeles, CA 90021
  [44] Capo                                | 1810 Ocean Ave, Santa Monica, CA 90401
  [45] Niku X                              | 900 Wilshire Blvd Ste 212, Los Angeles, CA 90017
  [46] Red Fish Restaurant                 | 8452 Melrose Ave, West Hollywood, CA 90069
  [47] Maison Kasai at Level 8             | 1254 S Figueroa St 8th Floor, Los Angeles, CA 90015
  [48] San Laurel                          | 100 S Grand Ave, Los Angeles, CA 90012
  [49] H&H Brazilian Steakhouse            | 518 W. 7th St., Los Angeles, CA 90014
  [50] The Biltmore Los Angeles            | 506 S Grand Ave, Los Angeles, CA 90071
  [51] Badmaash                            | 418 N Fairfax Ave, Los Angeles, CA 90036
  [52] Badmaash                            | 108 W 2nd St Apt 104, Los Angeles, CA 90012
  [53] Redbird                             | 114 E 2nd St, Los Angeles, CA 90012
  [54] Sushi Takeda                        | 123 Astronaut Ellison S Onizuka St ste 307 3rd floor, Los Angeles, CA 90012
  [55] Baroo                               | 905 E 2nd St #109, Los Angeles, CA 90012
  [56] Damian                              | 2132 E 7th Pl, Los Angeles, CA 90021
  [57] Majordomo                           | 1725 Naud St, Los Angeles, CA 90012
  [58] Girl & the Goat Los Angeles         | 555-3 Mateo St, Los Angeles, CA 90013
  [59] Parks BBQ                           | 955 S Vermont Ave Suite G, Los Angeles, CA 90006
  [60] Quarters BBQ                        | 3465 W 6th St, Los Angeles, CA 90020
  [61] Fleming's Steakhouse                | 800 W Olympic Blvd, Los Angeles, CA 90015
  [62] Aperture at City Club LA            | 555 S Flower St 51st Floor, Los Angeles, CA 90071
  [63] Steak 48                            | 9680 Wilshire Blvd Beverly Hills, CA 90212
  [64] The Arthur J                        | 903 Manhattan Ave. Manhattan Beach, CA 90266
  [65] The Belvedere                       | 9882 S Santa Monica Blvd Ground Floor, Beverly Hills, CA 90212
  [66] Elephante                           | 1332 2nd St Rooftop, Santa Monica, CA 90401
  [67] Nobu Malibu                         | 22706 Pacific Coast Hwy, Malibu, CA 90265
  [68] Nobu Los Angeles                    | 903 N La Cienega Blvd, Los Angeles, CA 90069
  [69] Yamashiro                           | 1999 N Sycamore Ave, Los Angeles, CA 90068
  [70] LouLou                              | 395 Santa Monica Pl #300, Santa Monica, CA 90401
  [71] Sushi Samba                         | 639 N La Peer Dr. West Hollywood, CA 90069
  [72] Spago by Wolfgang Puck              | 176 North Canon Drive Beverly Hills, CA, USA 90210
  [73] Lielle                              | 9575 W Pico Blvd Los Angeles, CA 90035
  [74] Bad Roman                           | 267 N Canon Dr Suite A7, Beverly Hills, CA 90210
  [75] Padi                                | 6464 W. Sunset Blvd Suite 120. Los Angeles, California 90028
  [76] Perse                               | 11677 San Vicente Blvd Unit 315, Los Angeles, CA 90049
  [77] Bar di Bello                        | 3300 Sunset Blvd #109-110, Los Angeles, CA 90026
  [78] The Lobster                         | 1602 Ocean Ave, Santa Monica, CA 90401
  [79] Castaway                            | 1250 E Harvard Rd, Burbank, CA 91501
  [80] Videre                              | 6317 Wilshire Blvd, Los Angeles, CA 90048
  [81] SALT Restaurant & Bar               | 13534 Bali Way, Marina Del Rey, CA 90292
  [82] Odyssey                             | 15600 Odyssey Dr, Granada Hills, CA 91344
  [83] Uca Terraza                         | 550 Flower St, Los Angeles, CA 90071
  [84] Sampa Los Angeles                   | 449 S Hewitt St, Los Angeles, CA 90013
  [85] RVR                                 | 1305 Abbot Kinney Blvd, Venice, CA 90291
  [86] Laurel Hardware                     | 7984 Santa Monica Blvd, West Hollywood, CA 90046
  [87] Crustacean                          | 468 N Bedford Dr, Beverly Hills, CA 90210
  [88] Mainro (MainR6)                     | 6350 Hollywood Blvd, Los Angeles, CA 90028
  [89] Broken Spanish Comedor              | 12565 Washington Blvd, Los Angeles, CA 90066
  [90] Night We Met                        | 788 S La Brea Ave, Los Angeles, CA 90036
  [91] Sora Craft Kitchen                  | 1109 East 12th Street, Los Angeles, CA 90021
  [92] Delilah                             | 7969 Santa Monica Blvd, West Hollywood, CA 90046
  [93] Catch LA                            | 8715 Melrose Ave, West Hollywood, CA 90069

=== ADDRESSES MISSING COMMA BEFORE STATE ===
⚠️  1 address(es) missing comma before CA:
                   Name                                    Address
41  Mastro's Ocean Club  18412 Pacific Coast Hwy., Malibu CA 90265

## 🛠️ Cell 12 — Fix Known Address Issues

**Issues identified during inspection:**
1. `Mastro's Ocean Club` — missing comma before `CA` in address  
2. `Morihiro` — listed in Echo Park but address has zip code `90012` (Downtown). Correct Echo Park zip is `90026`  
3. `Restaurant Ki`, `Rasarumah`, `H&H Brazilian` — trailing spaces in address (already fixed in Cell 9)

In [17]:
# --- Fix 1: Mastro's Ocean Club — add missing comma before CA ---
mastros_idx = df[df['Name'] == "Mastro's Ocean Club"].index
if not mastros_idx.empty:
    old_addr = df.loc[mastros_idx[0], 'Address']
    fixed_addr = old_addr.replace('Malibu CA', 'Malibu, CA')
    df.loc[mastros_idx[0], 'Address'] = fixed_addr
    print(f"✅ Fixed Mastro's Ocean Club address:")
    print(f"   Before: {old_addr}")
    print(f"   After : {fixed_addr}")

# --- Fix 2: Morihiro — correct zip code from 90012 (DTLA) to 90026 (Echo Park) ---
morihiro_idx = df[df['Name'] == 'Morihiro'].index
if not morihiro_idx.empty:
    old_addr = df.loc[morihiro_idx[0], 'Address']
    # Correct zip: Sunset Blvd near Echo Park is 90026
    fixed_addr = old_addr.replace('CA 90012', 'CA 90026')
    df.loc[morihiro_idx[0], 'Address'] = fixed_addr
    print(f"\n✅ Fixed Morihiro address zip code:")
    print(f"   Before: {old_addr}")
    print(f"   After : {fixed_addr}")

print("\n✅ Address fixes applied.")

✅ Fixed Mastro's Ocean Club address:
   Before: 18412 Pacific Coast Hwy., Malibu CA 90265
   After : 18412 Pacific Coast Hwy., Malibu, CA 90265

✅ Fixed Morihiro address zip code:
   Before: 1115 W. Sunset Blvd Suite 100 Los Angeles, CA 90012
   After : 1115 W. Sunset Blvd Suite 100 Los Angeles, CA 90026

✅ Address fixes applied.

## 📝 Cell 13 — Description Quality Check

Verifies all descriptions are meaningful (not too short) and unique.

In [18]:
# Word count per description
df['desc_word_count'] = df['Description'].str.split().str.len()

print("=== DESCRIPTION WORD COUNT STATS ===")
print(df['desc_word_count'].describe())

# Flag descriptions that are too short (< 10 words)
short_desc = df[df['desc_word_count'] < 10]
print(f"\n=== DESCRIPTIONS UNDER 10 WORDS ===")
if short_desc.empty:
    print("✅ All descriptions meet minimum word count (10+ words).")
else:
    print(f"⚠️  {len(short_desc)} description(s) are very short:")
    print(short_desc[['Name', 'Description', 'desc_word_count']].to_string())

# Check for duplicate descriptions
dupe_desc = df[df.duplicated('Description', keep=False)]
print(f"\n=== DUPLICATE DESCRIPTIONS ===")
if dupe_desc.empty:
    print("✅ All descriptions are unique.")
else:
    print(f"⚠️  {len(dupe_desc)} rows share identical descriptions:")
    print(dupe_desc[['Name', 'Description']].to_string())

=== DESCRIPTION WORD COUNT STATS ===
count    94.000000
mean     23.840426
std       4.723092
min      16.000000
25%      21.000000
50%      23.000000
75%      25.000000
max      46.000000
Name: desc_word_count, dtype: float64

=== DESCRIPTIONS UNDER 10 WORDS ===
✅ All descriptions meet minimum word count (10+ words).

=== DUPLICATE DESCRIPTIONS ===
✅ All descriptions are unique.

## 📞 Cell 14 — Telephone Number Validation

In [19]:
import re

print("=== TELEPHONE NUMBER FORMAT CHECK ===")

# Expected formats: (XXX) XXX-XXXX or 'Number Not Listed'
phone_pattern = re.compile(r'^\(\d{3}\) \d{3}-\d{4}$|^Number Not Listed$')

invalid_phones = df[~df['Telephone Number'].str.match(phone_pattern)]

if invalid_phones.empty:
    print("✅ All phone numbers are correctly formatted.")
else:
    print(f"⚠️  {len(invalid_phones)} phone number(s) with unexpected format:")
    print(invalid_phones[['Name', 'Telephone Number']].to_string())

# Summary of phone listing status
print(f"\n=== PHONE NUMBER STATUS ===")
listed = (df['Telephone Number'] != 'Number Not Listed').sum()
not_listed = (df['Telephone Number'] == 'Number Not Listed').sum()
print(f"  Listed       : {listed}")
print(f"  Not Listed   : {not_listed}")

=== TELEPHONE NUMBER FORMAT CHECK ===
✅ All phone numbers are correctly formatted.

=== PHONE NUMBER STATUS ===
  Listed       : 92
  Not Listed   : 2

## 💰 Cell 15 — Price Range Validation

In [20]:
print("=== PRICE RANGE DISTRIBUTION ===")

valid_prices = ['$', '$$', '$$$', '$$$$', '$$$$$']
price_counts = df['Price'].value_counts()

# Display in logical order
for price in valid_prices:
    count = price_counts.get(price, 0)
    bar = '█' * count
    print(f"  {price:<8} | {bar} ({count})")

# Check for invalid values
invalid_prices = df[~df['Price'].isin(valid_prices)]
if invalid_prices.empty:
    print("\n✅ All price values are valid.")
else:
    print(f"\n⚠️  {len(invalid_prices)} invalid price value(s):")
    print(invalid_prices[['Name', 'Price']].to_string())

=== PRICE RANGE DISTRIBUTION ===
  $        | ███ (3)
  $$       | █████████████ (13)
  $$$      | █████████████████████████ (25)
  $$$$     | ████████████████████████████████████████████████ (48)
  $$$$$    | █████ (5)

✅ All price values are valid.

## ⭐ Cell 16 — Michelin Guide Validation

In [21]:
print("=== MICHELIN GUIDE DISTRIBUTION ===")

valid_michelin = ['3-Star', '2-Star', '1-Star', 'Bib-Gourmand', 'Michelin-Selected', 'No']
michelin_order = ['3-Star', '2-Star', '1-Star', 'Bib-Gourmand', 'Michelin-Selected', 'No']
michelin_counts = df['Michelin-Guide'].value_counts()

for m in michelin_order:
    count = michelin_counts.get(m, 0)
    bar = '★' * count
    print(f"  {m:<20} | {bar} ({count})")

# Invalid check
invalid_michelin = df[~df['Michelin-Guide'].isin(valid_michelin)]
if invalid_michelin.empty:
    print("\n✅ All Michelin-Guide values are valid.")
else:
    print(f"\n⚠️  Unexpected Michelin values:")
    print(invalid_michelin[['Name', 'Michelin-Guide']].to_string())

# Show all Michelin starred restaurants
print("\n=== ALL MICHELIN-STARRED RESTAURANTS ===")
starred = df[df['Michelin-Guide'].isin(['3-Star', '2-Star', '1-Star'])].sort_values('Michelin-Guide')
print(starred[['Name', 'Location', 'Michelin-Guide', 'Price', 'Customer Ratings']].to_string(index=True))

=== MICHELIN GUIDE DISTRIBUTION ===
  3-Star               | ★★ (2)
  2-Star               | ★★★★ (4)
  1-Star               | ★★★★★★★★★★★★★★★★★★★★★ (21)
  Bib-Gourmand         | ★★★★★★★★★★ (10)
  Michelin-Selected    | ★★★★★★★★★★★★★★★ (15)
  No                   | ★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★ (42)

✅ All Michelin-Guide values are valid.

=== ALL MICHELIN-STARRED RESTAURANTS ===
                              Name                Location Michelin-Guide  Price  Customer Ratings
6                  Sushi Kaneyoshi            Little Tokyo         1-Star   $$$$               5.0
7                    Restaurant Ki            Little Tokyo         1-Star   $$$$               5.0
8                        715 Sushi    Downtown Los Angeles         1-Star   $$$$               5.0
9                   Orsa & Winston    Downtown Los Angeles         1-Star   $$$$               4.8
10                         Camphor    Downtown Los Angeles         1-Star   $$$$               4.7
11                        Morihiro               Echo Park         1-Star   $$$$               5.0
12                            Kato    Downtown Los Angeles         1-Star   $$$$               4.9
13                          Holbox       South Los Angeles         1-Star     $$               5.0
14  Gwen Butcher Shop & Restaurant               Hollywood         1-Star   $$$$               3.0
15                        Heritage              Long Beach         1-Star    $$$               4.0
16                     Sushi Inaba                Torrance         1-Star   $$$$               5.0
17                            Kali       Larchmont Village         1-Star    $$$               4.0
18                          Citrin            Santa Monica         1-Star    $$$               4.0
19                   Gucci Osteria           Beverly Hills         1-Star   $$$$               3.0
20                         Meteora               Hollywood         1-Star    $$$               4.0
21                     Mori Nozomi        West Los Angeles         1-Star   $$$$               5.0
22                      Nozawa Bar           Beverly Hills         1-Star   $$$$               4.0
23                     Pasta | Bar                  Encino         1-Star    $$$               3.0
24                      Shin Sushi                  Encino         1-Star   $$$$               4.0
25              Uka at Japan House               Hollywood         1-Star   $$$$               4.5
73                          Lielle             Los Angeles         1-Star   $$$$               4.7
2                           Hayato  Downtown Arts District         2-Star   $$$$               5.0
3                           n/naka                   Palms         2-Star   $$$$               5.0
4                          Melisse            Santa Monica         2-Star   $$$$               4.0
5                       Vespertine             Culver City         2-Star   $$$$               5.0
0                            Somni          West Hollywood         3-Star  $$$$$               5.0
1                       Providence               Hollywood         3-Star   $$$$               5.0

## 🌆 Cell 17 — Sky-High Rooftop & Atmosphere Validation

In [22]:
# Sky-High Rooftop check
print("=== SKY-HIGH ROOFTOP ===")
valid_rooftop = ['Yes', 'No']
print(df['Sky-High Rooftop'].value_counts())

invalid_rooftop = df[~df['Sky-High Rooftop'].isin(valid_rooftop)]
if invalid_rooftop.empty:
    print("✅ All Sky-High Rooftop values are valid.")
else:
    print("⚠️  Invalid values:", invalid_rooftop[['Name', 'Sky-High Rooftop']].to_string())

# Rooftop restaurants list
print("\n=== ROOFTOP / TOP-FLOOR RESTAURANTS ===")
rooftops = df[df['Sky-High Rooftop'] == 'Yes']
print(rooftops[['Name', 'Location', 'Dining Atmosphere', 'Price']].to_string(index=True))

# Dining Atmosphere check
print("\n=== DINING ATMOSPHERE DISTRIBUTION ===")
print(df['Dining Atmosphere'].value_counts())

valid_atmosphere = ['Fine-Dining', 'Trendy', 'Casual', 'Romantic', 
                    'Smart-Casual', 'Romantic / Smart-Casual', 'Trendy / Smart-Casual']
invalid_atm = df[~df['Dining Atmosphere'].isin(valid_atmosphere)]
if invalid_atm.empty:
    print("\n✅ All Dining Atmosphere values are valid.")
else:
    print("\n⚠️  Unexpected atmosphere values:")
    print(invalid_atm[['Name', 'Dining Atmosphere']].to_string())

=== SKY-HIGH ROOFTOP ===
Sky-High Rooftop
No     82
Yes    12
Name: count, dtype: int64
✅ All Sky-High Rooftop values are valid.

=== ROOFTOP / TOP-FLOOR RESTAURANTS ===
                        Name              Location        Dining Atmosphere Price
36                   71Above  Downtown Los Angeles              Fine-Dining  $$$$
40              La Boucherie  Downtown Los Angeles              Fine-Dining  $$$$
62  Aperture at City Club LA  Downtown Los Angeles              Fine-Dining  $$$$
66                 Elephante          Santa Monica                   Trendy  $$$$
69                 Yamashiro       Hollywood Hills  Romantic / Smart-Casual  $$$$
70                    LouLou          Santa Monica                   Casual  $$$$
71               Sushi Samba        West Hollywood    Trendy / Smart-Casual   $$$
79                  Castaway               Burbank             Smart-Casual   $$$
80                    Videre         Beverly Hills             Smart-Casual   $$$
82                   Odyssey         Granada Hills             Smart-Casual   $$$
83               Uca Terraza  Downtown Los Angeles                   Casual    $$
93                  Catch LA        West Hollywood  Romantic / Smart-Casual   $$$

=== DINING ATMOSPHERE DISTRIBUTION ===
Dining Atmosphere
Fine-Dining                43
Casual                     18
Trendy                     12
Romantic / Smart-Casual     6
Smart-Casual                4
Romantic                    3
Trendy / Smart-Casual       3
Upscale / Fine-Dining       2
Fine-Casual                 1
Trendy / Vibrant            1
Trendy / Casual             1
Name: count, dtype: int64

⚠️  Unexpected atmosphere values:
                      Name      Dining Atmosphere
76                   Perse  Upscale / Fine-Dining
78             The Lobster            Fine-Casual
88         Mainro (MainR6)       Trendy / Vibrant
89  Broken Spanish Comedor        Trendy / Casual
92                 Delilah  Upscale / Fine-Dining

## 🕐 Cell 18 — Reservations & Dress Code Validation

In [23]:
# Reservations check
print("=== RESERVATIONS DISTRIBUTION ===")
valid_reservations = ['Yes', 'No', 'Reservation Only']
print(df['Reservations'].value_counts())

invalid_res = df[~df['Reservations'].isin(valid_reservations)]
if invalid_res.empty:
    print("✅ All Reservations values are valid.")
else:
    print("⚠️  Unexpected values:", invalid_res[['Name', 'Reservations']].to_string())

# Dress Code check
print("\n=== DRESS CODE DISTRIBUTION ===")
valid_dresscode = ['Yes', 'No', 'Strict']
print(df['Dress Code'].value_counts())

invalid_dress = df[~df['Dress Code'].isin(valid_dresscode)]
if invalid_dress.empty:
    print("✅ All Dress Code values are valid.")
else:
    print("⚠️  Unexpected values:", invalid_dress[['Name', 'Dress Code']].to_string())

# Reservation-Only restaurants (most exclusive)
print("\n=== RESERVATION-ONLY RESTAURANTS ===")
res_only = df[df['Reservations'] == 'Reservation Only']
print(res_only[['Name', 'Location', 'Michelin-Guide', 'Price']].to_string(index=True))

=== RESERVATIONS DISTRIBUTION ===
Reservations
Yes                 50
Reservation Only    32
No                  12
Name: count, dtype: int64
✅ All Reservations values are valid.

=== DRESS CODE DISTRIBUTION ===
Dress Code
No        71
Yes       21
Strict     2
Name: count, dtype: int64
✅ All Dress Code values are valid.

=== RESERVATION-ONLY RESTAURANTS ===
                       Name                Location     Michelin-Guide  Price
0                     Somni          West Hollywood             3-Star  $$$$$
1                Providence               Hollywood             3-Star   $$$$
2                    Hayato  Downtown Arts District             2-Star   $$$$
3                    n/naka                   Palms             2-Star   $$$$
4                   Melisse            Santa Monica             2-Star   $$$$
5                Vespertine             Culver City             2-Star   $$$$
6           Sushi Kaneyoshi            Little Tokyo             1-Star   $$$$
7             Restaurant Ki            Little Tokyo             1-Star   $$$$
8                 715 Sushi    Downtown Los Angeles             1-Star   $$$$
9            Orsa & Winston    Downtown Los Angeles             1-Star   $$$$
10                  Camphor    Downtown Los Angeles             1-Star   $$$$
11                 Morihiro               Echo Park             1-Star   $$$$
12                     Kato    Downtown Los Angeles             1-Star   $$$$
15                 Heritage              Long Beach             1-Star    $$$
16              Sushi Inaba                Torrance             1-Star   $$$$
20                  Meteora               Hollywood             1-Star    $$$
21              Mori Nozomi        West Los Angeles             1-Star   $$$$
22               Nozawa Bar           Beverly Hills             1-Star   $$$$
23              Pasta | Bar                  Encino             1-Star    $$$
24               Shin Sushi                  Encino             1-Star   $$$$
25       Uka at Japan House               Hollywood             1-Star   $$$$
45                   Niku X    Downtown Los Angeles                 No  $$$$$
47  Maison Kasai at Level 8    Downtown Los Angeles                 No   $$$$
54             Sushi Takeda            Little Tokyo  Michelin-Selected   $$$$
55                    Baroo    Downtown Los Angeles  Michelin-Selected   $$$$
72   Spago by Wolfgang Puck           Beverly Hills                 No   $$$$
73                   Lielle             Los Angeles             1-Star   $$$$
84        Sampa Los Angeles    Downtown Los Angeles  Michelin-Selected   $$$$
87               Crustacean           Beverly Hills  Michelin-Selected   $$$$
88          Mainro (MainR6)               Hollywood                 No   $$$$
91       Sora Craft Kitchen    Downtown Los Angeles  Michelin-Selected    $$$
92                  Delilah          West Hollywood                 No    $$$

## ⭐ Cell 19 — Customer Ratings Validation

In [24]:
print("=== CUSTOMER RATINGS VALIDATION ===")

# Valid range: 1.0 to 5.0
out_of_range = df[(df['Customer Ratings'] < 1.0) | (df['Customer Ratings'] > 5.0)]
if out_of_range.empty:
    print("✅ All Customer Ratings are within valid range (1.0–5.0).")
else:
    print(f"⚠️  {len(out_of_range)} rating(s) out of range:")
    print(out_of_range[['Name', 'Customer Ratings']].to_string())

print("\n=== RATING SUMMARY ===")
print(f"  Average Rating : {df['Customer Ratings'].mean():.2f}")
print(f"  Highest Rating : {df['Customer Ratings'].max()} ({df[df['Customer Ratings'] == df['Customer Ratings'].max()]['Name'].tolist()})")
print(f"  Lowest Rating  : {df['Customer Ratings'].min()} ({df[df['Customer Ratings'] == df['Customer Ratings'].min()]['Name'].tolist()})")

print("\n=== TOP 10 HIGHEST RATED RESTAURANTS ===")
top10 = df.nlargest(10, 'Customer Ratings')[['Name', 'Location', 'Michelin-Guide', 'Price', 'Customer Ratings']]
print(top10.to_string(index=True))

=== CUSTOMER RATINGS VALIDATION ===
✅ All Customer Ratings are within valid range (1.0–5.0).

=== RATING SUMMARY ===
  Average Rating : 4.50
  Highest Rating : 5.0 (['Somni', 'Providence', 'Hayato', 'n/naka', 'Vespertine', 'Sushi Kaneyoshi', 'Restaurant Ki', '715 Sushi', 'Morihiro', 'Holbox', 'Sushi Inaba', 'Mori Nozomi', 'CUT by Wolfgang Puck', 'Chi Spacca', 'Capo', 'Niku X'])
  Lowest Rating  : 3.0 (['Gwen Butcher Shop & Restaurant', 'Gucci Osteria', 'Pasta | Bar'])

=== TOP 10 HIGHEST RATED RESTAURANTS ===
               Name                Location Michelin-Guide  Price  Customer Ratings
0             Somni          West Hollywood         3-Star  $$$$$               5.0
1        Providence               Hollywood         3-Star   $$$$               5.0
2            Hayato  Downtown Arts District         2-Star   $$$$               5.0
3            n/naka                   Palms         2-Star   $$$$               5.0
5        Vespertine             Culver City         2-Star   $$$$               5.0
6   Sushi Kaneyoshi            Little Tokyo         1-Star   $$$$               5.0
7     Restaurant Ki            Little Tokyo         1-Star   $$$$               5.0
8         715 Sushi    Downtown Los Angeles         1-Star   $$$$               5.0
11         Morihiro               Echo Park         1-Star   $$$$               5.0
13           Holbox       South Los Angeles         1-Star     $$               5.0

## 🤖 Cell 20 — Create `restaurant_metadata` Column for LLM/Embedding Use

This column combines key restaurant metadata into a single enriched text string.  
It will be used as input to the sentence embedding model (`all-MiniLM-L6-v2`)  
for semantic search and LLM-based recommendation retrieval.

In [25]:
def build_restaurant_metadata(row):
    """
    Combines restaurant metadata into a rich text string for embedding.
    Format: '[Name] is a [Cuisine Type] restaurant in [Location], [CA].
             [Description] Price: [Price]. Atmosphere: [Atmosphere].
             Michelin: [Michelin]. Rating: [Rating]/5."
    """
    michelin_text = (
        f"Michelin {row['Michelin-Guide']}" 
        if row['Michelin-Guide'] not in ['No', 'Michelin-Selected'] 
        else row['Michelin-Guide']
    )
    rooftop_text = " Rooftop/top-floor dining." if row['Sky-High Rooftop'] == 'Yes' else ""
    
    return (
        f"{row['Name']} is a {row['Cuisine Type']} restaurant located in "
        f"{row['Location']}, Los Angeles. {row['Description']} "
        f"Price range: {row['Price']}. Atmosphere: {row['Dining Atmosphere']}. "
        f"Michelin Guide: {michelin_text}. Customer Rating: {row['Customer Ratings']}/5."
        f"{rooftop_text}"
    )

df['restaurant_metadata'] = df.apply(build_restaurant_metadata, axis=1)

print("✅ 'restaurant_metadata' column created.")
print("\n=== SAMPLE RESTAURANT METADATA ===")
for i in [0, 6, 13, 26, 36]:  # Sample: Somni, Sushi Kaneyoshi, Holbox, Maccheroni, 71Above
    print(f"\n[{df.loc[i, 'Name']}]")
    print(f"  {df.loc[i, 'restaurant_metadata']}")

✅ 'restaurant_metadata' column created.

=== SAMPLE RESTAURANT METADATA ===

[Somni]
  Somni is a Spanish Modernist restaurant located in West Hollywood, Los Angeles. A 14-seat Spanish Modernist chef's counter offering a 20+ course tasting menu led by Chef Aitor Zabala with one seating per night. Price range: $$$$$. Atmosphere: Fine-Dining. Michelin Guide: Michelin 3-Star. Customer Rating: 5.0/5.

[Sushi Kaneyoshi]
  Sushi Kaneyoshi is a Japanese / Sushi restaurant located in Little Tokyo, Los Angeles. A highly exclusive omakase sushi experience tucked in Little Tokyo offering pristine seasonal fish in an intimate counter setting. Price range: $$$$. Atmosphere: Fine-Dining. Michelin Guide: Michelin 1-Star. Customer Rating: 5.0/5.

[Holbox]
  Holbox is a Mexican / Seafood restaurant located in South Los Angeles, Los Angeles. A Yucatecan-style seafood counter from Chef Gilberto Cetina Jr. inside Mercado La Paloma offering some of LA's most delicious and affordable Michelin-starred food. Price range: $$. Atmosphere: Casual. Michelin Guide: Michelin 1-Star. Customer Rating: 5.0/5.

[Maccheroni Republic]
  Maccheroni Republic is a Italian-American restaurant located in Downtown Los Angeles, Los Angeles. A Michelin Bib Gourmand Italian-American trattoria offering rustic handmade pastas and classic Italian dishes in a warm casual setting. Price range: $$. Atmosphere: Casual. Michelin Guide: Michelin Bib-Gourmand. Customer Rating: 4.5/5.

[71Above]
  71Above is a Contemporary American restaurant located in Downtown Los Angeles, Los Angeles. A breathtaking contemporary American fine dining restaurant on the 71st floor of the US Bank Tower offering sweeping panoramic views from Malibu to the mountains. Price range: $$$$. Atmosphere: Fine-Dining. Michelin Guide: No. Customer Rating: 4.7/5. Rooftop/top-floor dining.

## 📋 Cell 21 — Full Dataset Review (All 100 Restaurants)

In [26]:
print("=== COMPLETE CLEANED DATASET ===")
display_cols = [
    'Name', 'Location', 'Price', 'Cuisine Type', 
    'Dining Atmosphere', 'Michelin-Guide', 'Customer Ratings', 
    'Sky-High Rooftop', 'Reservations', 'Dress Code'
]
df[display_cols]

=== COMPLETE CLEANED DATASET ===

                              Name                Location  Price                        Cuisine Type        Dining Atmosphere     Michelin-Guide  Customer Ratings Sky-High Rooftop      Reservations Dress Code
0                            Somni          West Hollywood  $$$$$                   Spanish Modernist              Fine-Dining             3-Star               5.0               No  Reservation Only         No
1                       Providence               Hollywood   $$$$              Seafood / Contemporary              Fine-Dining             3-Star               5.0               No  Reservation Only         No
2                           Hayato  Downtown Arts District   $$$$                    Japanese Kaiseki              Fine-Dining             2-Star               5.0               No  Reservation Only         No
3                           n/naka                   Palms   $$$$                    Japanese Kaiseki              Fine-Dining             2-Star               5.0               No  Reservation Only     Strict
4                          Melisse            Santa Monica   $$$$      French / Contemporary American              Fine-Dining             2-Star               4.0               No  Reservation Only        Yes
5                       Vespertine             Culver City   $$$$  Contemporary American / Innovative              Fine-Dining             2-Star               5.0               No  Reservation Only         No
6                  Sushi Kaneyoshi            Little Tokyo   $$$$                    Japanese / Sushi              Fine-Dining             1-Star               5.0               No  Reservation Only         No
7                    Restaurant Ki            Little Tokyo   $$$$                 Korean Contemporary              Fine-Dining             1-Star               5.0               No  Reservation Only         No
8                        715 Sushi    Downtown Los Angeles   $$$$                    Japanese / Sushi              Fine-Dining             1-Star               5.0               No  Reservation Only         No
9                   Orsa & Winston    Downtown Los Angeles   $$$$                        Contemporary              Fine-Dining             1-Star               4.8               No  Reservation Only         No
10                         Camphor    Downtown Los Angeles   $$$$                              French              Fine-Dining             1-Star               4.7               No  Reservation Only         No
11                        Morihiro               Echo Park   $$$$                            Japanese              Fine-Dining             1-Star               5.0               No  Reservation Only         No
12                            Kato    Downtown Los Angeles   $$$$                   Asian / Taiwanese                   Trendy             1-Star               4.9               No  Reservation Only         No
13                          Holbox       South Los Angeles     $$                   Mexican / Seafood                   Casual             1-Star               5.0               No               Yes         No
14  Gwen Butcher Shop & Restaurant               Hollywood   $$$$                 American Steakhouse              Fine-Dining             1-Star               3.0               No               Yes         No
15                        Heritage              Long Beach    $$$                         Californian                 Romantic             1-Star               4.0               No  Reservation Only         No
16                     Sushi Inaba                Torrance   $$$$                    Japanese Omakase              Fine-Dining             1-Star               5.0               No  Reservation Only         No
17                            Kali       Larchmont Village    $$$                         Californian                 Romantic             1-Star               4.0               No               Yes         No
18                          Citrin            Santa Monica    $$$               Contemporary American              Fine-Dining             1-Star               4.0               No               Yes         No
19                   Gucci Osteria           Beverly Hills   $$$$                             Italian              Fine-Dining             1-Star               3.0               No               Yes         No
20                         Meteora               Hollywood    $$$               Global / Contemporary                   Trendy             1-Star               4.0               No  Reservation Only         No
21                     Mori Nozomi        West Los Angeles   $$$$                    Japanese Omakase              Fine-Dining             1-Star               5.0               No  Reservation Only         No
22                      Nozawa Bar           Beverly Hills   $$$$                    Japanese Omakase              Fine-Dining             1-Star               4.0               No  Reservation Only         No
23                     Pasta | Bar                  Encino    $$$                             Italian              Fine-Dining             1-Star               3.0               No  Reservation Only         No
24                      Shin Sushi                  Encino   $$$$                    Japanese Omakase              Fine-Dining             1-Star               4.0               No  Reservation Only         No
25              Uka at Japan House               Hollywood   $$$$                    Japanese Kaiseki              Fine-Dining             1-Star               4.5               No  Reservation Only         No
26             Maccheroni Republic    Downtown Los Angeles     $$                    Italian-American                   Casual       Bib-Gourmand               4.5               No               Yes         No
27             The Factory Kitchen    Downtown Los Angeles     $$                             Italian                   Trendy       Bib-Gourmand               4.6               No               Yes         No
28                 Pizzeria Bianco    Downtown Los Angeles     $$                               Pizza                   Casual       Bib-Gourmand               4.7               No               Yes         No
29                         Tsubaki               Echo Park     $$                            Japanese                   Trendy       Bib-Gourmand               4.7               No               Yes         No
30                        Langer's                Westlake     $$                                Deli                   Casual       Bib-Gourmand               4.8               No                No         No
31            Moo's Craft Barbecue         Lincoln Heights     $$                            Barbecue                   Casual       Bib-Gourmand               4.7               No                No         No
32                       Rasarumah             Los Angeles    $$$                           Malaysian                   Casual       Bib-Gourmand               4.8               No               Yes         No
33                           Komal             Los Angeles      $                             Mexican                   Casual       Bib-Gourmand               4.8               No               Yes         No
34                    Pine & Crane    Downtown Los Angeles      $                   Asian / Taiwanese                   Casual       Bib-Gourmand               4.6               No               Yes         No
35                    Pine & Crane             Silver Lake      $                   Asian / Taiwanese                   Casual       Bib-Gourmand               4.6               No               Yes         No
36                         71Above    Downtown Los Angeles   $$$$               Contemporary American              Fine-Dining                 No               4.7              Yes               Yes        Yes
37            CUT by Wolfgang Puck           Beverly Hills   $$$$                          Steakhouse              Fine-Dining                 No               5.0               No               Yes        Yes
38                   Osteria Mozza               Hollywood   $$$$                             Italian              Fine-Dining                 No               4.9               No               Yes         No
39                      Chi Spacca               Hollywood   $$$$                    Italian / Tuscan              Fine-Dining                 No               5.0               No               Yes         No
40                    La Boucherie    Downtown Los Angeles   $$$$                          Steakhouse              Fine-Dining                 No               4.5              Yes               Yes        Yes
41             Mastro's Ocean Club                  Malibu   $$$$                Steakhouse / Seafood              Fine-Dining                 No               4.4               No               Yes        Yes
42                     Ocean Prime           Beverly Hills   $$$$                Seafood / Steakhouse              Fine-Dining                 No               4.7               No               Yes        Yes
43                          Bestia  Downtown Arts District   $$$$                             Italian                   Trendy                 No               4.8               No               Yes         No
44                            Capo            Santa Monica   $$$$                 Italian / Modernist                 Romantic                 No               5.0               No               Yes         No
45                          Niku X    Downtown Los Angeles  $$$$$               Japanese / Steakhouse              Fine-Dining                 No               5.0               No  Reservation Only        Yes
46             Red Fish Restaurant          West Hollywood   $$$$                  Steakhouse / Sushi                   Trendy                 No               4.8               No               Yes         No
47         Maison Kasai at Level 8    Downtown Los Angeles   $$$$                          Teppanyaki              Fine-Dining                 No               4.3               No  Reservation Only         No
48                      San Laurel    Downtown Los Angeles   $$$$                             Spanish              Fine-Dining                 No               4.5               No               Yes         No
49        H&H Brazilian Steakhouse    Downtown Los Angeles   $$$$                Brazilian Steakhouse              Fine-Dining                 No               4.3               No               Yes         No
50        The Biltmore Los Angeles    Downtown Los Angeles   $$$$                            American              Fine-Dining                 No               4.4               No               Yes         No
51                        Badmaash               Hollywood     $$                              Indian                   Casual  Michelin-Selected               4.3               No               Yes         No
52                        Badmaash    Downtown Los Angeles     $$                              Indian                   Casual  Michelin-Selected               3.9               No               Yes         No
53                         Redbird    Downtown Los Angeles    $$$                        Contemporary              Fine-Dining  Michelin-Selected               4.5               No               Yes         No
54                    Sushi Takeda            Little Tokyo   $$$$                            Japanese              Fine-Dining  Michelin-Selected               4.6               No  Reservation Only         No
55                           Baroo    Downtown Los Angeles   $$$$                 Korean Contemporary                   Trendy  Michelin-Selected               4.5               No  Reservation Only         No
56                          Damian    Downtown Los Angeles    $$$                             Mexican              Fine-Dining  Michelin-Selected               4.6               No               Yes         No
57                       Majordomo               Chinatown    $$$                               Asian                   Trendy  Michelin-Selected               4.2               No               Yes         No
58     Girl & the Goat Los Angeles    Downtown Los Angeles    $$$                        Contemporary                   Trendy  Michelin-Selected               4.4               No               Yes         No
59                       Parks BBQ               Koreatown    $$$                              Korean                   Casual  Michelin-Selected               4.5               No               Yes         No
60                    Quarters BBQ               Koreatown    $$$                              Korean                   Casual  Michelin-Selected               4.3               No               Yes         No
61            Fleming's Steakhouse    Downtown Los Angeles   $$$$                          Steakhouse              Fine-Dining                 No               4.6               No               Yes        Yes
62        Aperture at City Club LA    Downtown Los Angeles   $$$$               Contemporary American              Fine-Dining                 No               4.2              Yes               Yes        Yes
63                        Steak 48           Beverly Hills   $$$$                          Steakhouse              Fine-Dining                 No               4.6               No               Yes     Strict
64                    The Arthur J         Manhattan Beach   $$$$                          Steakhouse              Fine-Dining                 No               4.6               No                No         No
65                   The Belvedere           Beverly Hills  $$$$$  Mediterranean / French-Californian             Smart-Casual                 No               4.5               No               Yes         No
66                       Elephante            Santa Monica   $$$$                             Italian                   Trendy  Michelin-Selected               4.6              Yes               Yes         No
67                     Nobu Malibu                  Malibu  $$$$$                 Japanese / Peruvian  Romantic / Smart-Casual                 No               4.3               No               Yes         No
68                Nobu Los Angeles          West Hollywood  $$$$$                 Japanese / Peruvian    Trendy / Smart-Casual                 No               4.3               No               Yes         No
69                       Yamashiro         Hollywood Hills   $$$$                    Japanese / Sushi  Romantic / Smart-Casual                 No               4.3              Yes               Yes        Yes
70                          LouLou            Santa Monica   $$$$              French / Mediterranean                   Casual                 No               4.3              Yes               Yes         No
71                     Sushi Samba          West Hollywood    $$$                Japanese / Brazilian    Trendy / Smart-Casual                 No               4.7              Yes                No         No
72          Spago by Wolfgang Puck           Beverly Hills   $$$$                             Italian              Fine-Dining                 No               4.5               No  Reservation Only        Yes
73                          Lielle             Los Angeles   $$$$                  Nordic-Californian              Fine-Dining             1-Star               4.7               No  Reservation Only        Yes
74                       Bad Roman           Beverly Hills    $$$                 Italian / Modernist    Trendy / Smart-Casual                 No               4.9               No                No        Yes
75                            Padi               Hollywood     $$                  Asian / Indonesian                   Casual                 No               4.9               No                No         No
76                           Perse               Brentwood    $$$                             Persian    Upscale / Fine-Dining                 No               4.5               No               Yes         No
77                    Bar di Bello             Silver Lake   $$$$                  Italian / Milanese  Romantic / Smart-Casual                 No               4.6               No               Yes        Yes
78                     The Lobster            Santa Monica    $$$                             Seafood              Fine-Casual  Michelin-Selected               4.3               No                No         No
79                        Castaway                 Burbank    $$$                Steakhouse / Seafood             Smart-Casual                 No               4.6              Yes               Yes        Yes
80                          Videre           Beverly Hills    $$$               Contemporary American             Smart-Casual                 No               4.2              Yes                No         No
81           SALT Restaurant & Bar          Marina Del Rey     $$     Contemporary American / Seafood                   Casual                 No               4.2               No               Yes         No
82                         Odyssey           Granada Hills    $$$           New American / Steakhouse             Smart-Casual                 No               4.3              Yes               Yes         No
83                     Uca Terraza    Downtown Los Angeles     $$                New American / Latin                   Casual                 No               3.8              Yes                No         No
84               Sampa Los Angeles    Downtown Los Angeles   $$$$                Asian / New American                   Trendy  Michelin-Selected               4.5               No  Reservation Only         No
85                             RVR                  Venice     $$                    Japanese Izakaya                   Casual                 No               4.1               No               Yes         No
86                 Laurel Hardware          West Hollywood    $$$                        New American                   Trendy                 No               3.9               No                No         No
87                      Crustacean           Beverly Hills   $$$$                  Asian / Vietnamese              Fine-Dining  Michelin-Selected               4.7               No  Reservation Only        Yes
88                 Mainro (MainR6)               Hollywood   $$$$                        Asian Fusion         Trendy / Vibrant                 No               4.1               No  Reservation Only        Yes
89          Broken Spanish Comedor             Culver City    $$$                         New Mexican          Trendy / Casual                 No               4.7               No                No         No
90                    Night We Met             Los Angeles    $$$                           Pan Asian  Romantic / Smart-Casual                 No               4.4               No                No        Yes
91              Sora Craft Kitchen    Downtown Los Angeles    $$$                             Turkish  Romantic / Smart-Casual  Michelin-Selected               4.8               No  Reservation Only        Yes
92                         Delilah          West Hollywood    $$$                        New American    Upscale / Fine-Dining                 No               4.1               No  Reservation Only        Yes
93                        Catch LA          West Hollywood    $$$            Japanese /  New American  Romantic / Smart-Casual                 No               4.7              Yes               Yes        Yes

## 📊 Cell 22 — Final Data Summary Report

In [27]:
print("="*60)
print("   FINAL DATASET SUMMARY REPORT")
print("="*60)
print(f"  Total Restaurants        : {len(df)}")
print(f"  Total Columns            : {len(df.columns)}")
print(f"  Missing Values           : {df.drop(columns=['desc_word_count']).isnull().sum().sum()}")
print(f"  Exact Duplicate Rows     : {df.duplicated(subset=['Name','Address']).sum()}")
print()
print("  --- Michelin Breakdown ---")
for m in ['3-Star', '2-Star', '1-Star', 'Bib-Gourmand', 'Michelin-Selected', 'No']:
    count = (df['Michelin-Guide'] == m).sum()
    print(f"  {m:<22}: {count}")
print()
print("  --- Price Breakdown ---")
for p in ['$$$$$', '$$$$', '$$$', '$$', '$']:
    count = (df['Price'] == p).sum()
    print(f"  {p:<22}: {count}")
print()
print(f"  Average Customer Rating  : {df['Customer Ratings'].mean():.2f} / 5.0")
print(f"  Rooftop Restaurants      : {(df['Sky-High Rooftop'] == 'Yes').sum()}")
print(f"  Reservation-Only Spots   : {(df['Reservations'] == 'Reservation Only').sum()}")
print(f"  Strict Dress Code        : {(df['Dress Code'] == 'Strict').sum()}")
print()
print(f"  restaurant_metadata      : {df['restaurant_metadata'].notna().sum()} / {len(df)} created")
print("="*60)
print("  ✅ Dataset is clean and ready for vector embedding!")
print("="*60)

============================================================
   FINAL DATASET SUMMARY REPORT
============================================================
  Total Restaurants        : 94
  Total Columns            : 16
  Missing Values           : 0
  Exact Duplicate Rows     : 0

  --- Michelin Breakdown ---
  3-Star                : 2
  2-Star                : 4
  1-Star                : 21
  Bib-Gourmand          : 10
  Michelin-Selected     : 15
  No                    : 42

  --- Price Breakdown ---
  $$$$$                 : 5
  $$$$                  : 48
  $$$                   : 25
  $$                    : 13
  $                     : 3

  Average Customer Rating  : 4.50 / 5.0
  Rooftop Restaurants      : 12
  Reservation-Only Spots   : 32
  Strict Dress Code        : 2

  restaurant_metadata      : 94 / 94 created
============================================================
  ✅ Dataset is clean and ready for vector embedding!
============================================================

## 💾 Cell 23 — Export Cleaned Dataset

Saves the final cleaned and enriched dataset.  
The temporary helper column `desc_word_count` is dropped before export.

In [28]:

df_final = df.drop(columns=['desc_word_count'])


output_path = "../data/cleaned_restaurants_final.csv"
df_final.to_csv(output_path, index=False)

print(f"✅ Cleaned dataset exported to: {output_path}")
print(f"   Rows    : {df_final.shape[0]}")
print(f"   Columns : {df_final.shape[1]}")
print(f"\nFinal columns:")
for i, col in enumerate(df_final.columns, 1):
    print(f"   {i:>2}. {col}")

print("\n🚀 Next step: Use cleaned_restaurants_final.csv in notebook 2 — Vector Embedding & Semantic Search")

✅ Cleaned dataset exported to: ../data/cleaned_restaurants_final.csv
   Rows    : 94
   Columns : 15

Final columns:
    1. Name
    2. Location
    3. Description
    4. Address
    5. Telephone Number
    6. Price
    7. Cuisine Type
    8. Dining Atmosphere
    9. Sky-High Rooftop
   10. Michelin-Guide
   11. Customer Ratings
   12. Operation Hours
   13. Reservations
   14. Dress Code
   15. restaurant_metadata

🚀 Next step: Use cleaned_restaurants_final.csv in notebook 2 — Vector Embedding & Semantic Search